### ISSUE TITLE
As an admin, I would like to utilize slax on open source repos without giving access to private repos, so that my contributors can have less FUD about authoring

### ISSUE THREAD

**Issue by thomasknoll** [revelrylabs/slax#11]
## Background

Currently, running /auth and using the /issue command in slack requires the user giving permission to all private repos. We would like to make this more accessible to people contributing to our open source repos. The current version puts up a barrier to entry for anyone who cares about privacy and security (which is hopefully a lot of people)

## Scenario: Admin/ Setup
- Given I am the admin of a slack account
- And I am the admin of a GitHub repo
- And I want to setup slax for my project
- [ ] When I … 
- [ ] Then running `/auth` in the slack channel will only request user permissions on public repos

## Scenario: User/Contributor
- Given I am a member of the connected slack account
- And I am a contributor on the connected GitHub repo 
- [ ] When I run `/auth` in the slack channel
- [ ] Then GitHub only requests permissions on public repos

**Comment by thomasknoll** [comment]
I don’t know whether we need two different versions of tool — one for public only, and a second for private and public — or whether there is a way to further customize the service to accommodate both scenarios. So, before I finalize the AC here, I would like to talk shop with @lukeledet.

If it’s easy to throw some notes in here, that works for me. If you’d like to talk through it a bit, anything open here is good for me: http://calendly.com/tk/revsync

**Comment by lukeledet** [comment]
@thomasknoll This is done!
