### ISSUE TITLE
Housekeeping - let's make all the Rev open source repos consistent!

### ISSUE THREAD

**Issue by radditude** [revelrylabs/slax#12]
There's still a few things left to do in order to make this repo an awesome place to contribute. Checklist as follows:

- [x] Readme
	- [x] Links to license
- [x] CI (Travis)
  - [x] Automatic deploy is set up (is that something we want for slax?)
- [x] Is hooked up to a channel somewhere so we get notifications about issues/PRs
- [x] Issue template (optional but encouraged) - http://wiki.revelry.co/index.php/Open_Source_Issue_Template

**Comment by bryanjos** [comment]
All have been completed. Closing.
