### ISSUE TITLE
Update base urls for lintron and the board checker

### ISSUE THREAD

**Issue by radditude** [revelrylabs/slax#20]
I noticed while setting up a new project that the default urls for the lintron webhook and the board checker webhook that get set up via the `/project` command are pointing to Heroku apps. We should update those so they point to the correct destination now that lintron and slack-agile are hosted in our cluster.

If I'm reading [this code](https://github.com/revelrylabs/slax/blob/0b38fc172f1683d345ac8bd2966a94f8ff2e77ee/lib/slax/commands/project.ex#L193) correctly, all someone needs to do is update the `lintron` and `board_checker` environment variables to point to the cluster instances of those apps.

**Comment by bryanjos** [comment]
Done!
