### ISSUE TITLE
Add slash commands for adding github access tokens to the DB

### ISSUE THREAD

**Issue by BunnyDunker** [revelrylabs/slax#314]
**I'm submitting a ...**
  - [x] feature request

**What is the expected behavior?**
Users should be able to use slash commands to CRUD fine grained github access tokens and link them to repos

*Token commands:*
/token add [org/repo or repo] token
/token remove [org/repo or repo or token]
/token lookup [org/repo or repo]
/token update [org/repo or repo] token

Open questions:
- Would it also be useful to store the expiration date for the token? (potentially adding reminders for when they expire / are close to expiring)
- Since these tokens can grant access to more than one repo do we want to allow the connection of a token to more than one repo?
- Not certain on the feasibility of this yet but thoughts on when a create or update happens to have slax test the access token immediately to make sure it has the proper permissions before continuing?
- Do we want to associate channels to the pair as well?

Additional functionality ideas:
- Make poker start command return a message saying no access token is set when there is no entry for the selected repo

**Comment by BunnyDunker** [comment]
On the associate channels, I was thinking in case there needs to be a connection between a repo and a channel for the purposes of poker, but thinking on it further I don't think there is, I was probably mixing up issue lookup which eventually needs that so we can lookup issues with a number alone

**Comment by grossvogel** [comment]
Couple of thoughts here:
- In prodops we're making an API call to validate tokens when they're added. It doesn't need to be foolproof, and we don't want it to be destructive, but it's nice to check
- If we can get the expiration date from an API endpoint, that'd be great (and maybe that endpoint could also give us permission info useful for the above), but the fallback feature is: if Slax tries to _use_ an expired token at any point, the user should get a very helpful and clear error message.
- Might as well try to make the `/token add` command accept space-separate list of repos, but we can always pare back our ambitions if it gets out of hand
- I could definitely see a value in a feature to set a default repo for a particular channel, but that'd be a separate enhancement

**Comment by BunnyDunker** [comment]
Nick Amanda and I just had a call and I'm going to timebox getting an interface like peerbot for inserting the data, and if not we'll set up a basic web interface behind some basic auth to handle it

**Comment by BunnyDunker** [comment]
This one might be a bit awkward to QA since there is no remove functionality in as far as I know (only create and update, no lookup or remove). I would suggest creating some dummy github repos with issues and use the `/token` command.

- start by using the issue lookup pattern to make sure the repo is not already set up (slax should reply with an error message)
- enter the command `/token`
- click `Create Repo` and a the modal should change
- enter a project name or select an existing project (preferably not one we are using)
- enter the repo name with the pattern `org/repo` ex: `revelrylabs/slax`
- select the newly setup repo on the original modal
- enter the fine grained access token for the repo you set up and it's expiration date
- in any channel use the issue lookup pattern to test the access token's usage `repo#issueNumber` or `org/repo#issueNumber` for non revelrylabs orgs and slax should send an issue message to that channel.

**Comment by texastoast** [comment]
this works as designed, issue #384 created for future enhancement (confusing field labels can cause errors). Moving to ready to ship.
