### ISSUE TITLE
Add reminders for access token expiration

### ISSUE THREAD

**Issue by BunnyDunker** [revelrylabs/slax#327]
**I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

**What is the expected behavior?**
When an access token is within X amount of time from it's expiration date, Slax should post a message reminding users to update the access token.

**Comment by BunnyDunker** [comment]
As I'm implementing this I'm thinking of some open questions I have / could use input on:

First is the destination the reminders:
- We can have the reminders get sent to the channel associated with the repo but that would require a tiny bit extra implementation time in creating another modal for making the channel <-> project connection that is already setup in the DB. This would also be work towards one of the final features that have been discussed which is a channel's default repo so user's can just type in the issue number alone for issue lookup.
- Even with the above a default destination is needed so the question is what is an appropriate channel for that? 'Devtools' maybe? And for the sake of breaking things apart we can start with only the default if we want to pause implementation here.

The contents of the reminders:
- Should the contents of the message contain an `@here` to alert the whole channel?
- So far my message template looks like this: "Access token for repo: org_name/repo_name will expire on 9-20-2023, please replace it using the /token command" thoughts?

The frequency:
- My thoughts were to have the reminder job run every day and send a message if an access token's expiration date is older than 3 days from today (that includes three days in the future and the past), and for the sake of simplicity right now I have the same message being sent even if it is currently past the date. I set it to 3 days so it would notify before the weekend.
- With this setup the reminders will be sent every day until the issue is fixed, is this how we want it? We can set it up so it will only send out one reminder per repo, which if we keep the current check will only send a message 3 days before it expires
- I haven't yet looked at the time the reminder gets sent out but I assume I can default it to noon central time

**Comment by amandaphu** [comment]
i actually created a token for all the repos listed [here](https://revelrylabs.slack.com/archives/CS0F8K8GH/p1695153577139969). i figured it'd be best to have expirations in sync to make things easier. maybe next all hands we can have everyone create a repo/project and connect the token. i can upload the token in keybase

**Comment by grossvogel** [comment]
I don't think we want this to be too overbearing. The worst that happens is the token expires and somebody has to set it up again when they notice it's not working. So I would lean toward
- leaving out the `@here`
- only notifying once per _token_ rather than once per _repo_ if we can
- not many people are in #devtools though... maybe #helpdesk or #implementation would be better? In any case, let's not worry about repo <-> channel associations _yet_
- I think one reminder per token would be best, because we may want to ignore some and let them expire. but also one reminder per day for 3 days (with the final one saying it's expired?) would be fine. I'm thinking about Amanda's skeleton key token creating a deluge of reminders and making us all crazy for a week

**Comment by BunnyDunker** [comment]
Took all this in and instead of per token I grouped them by date so there will only ever be up to 4 messages at a time, one for the current day and each of the next three days of expiring tokens

**Comment by quinnmccourt** [comment]
@BunnyDunker how do you suggest this be QA'd?

**Comment by BunnyDunker** [comment]
The scheduler for these notifications runs every weekday at noon (central time) posting a single message for each of the access tokens that are expiring on this day, and an extra message for the access tokens expiring in the next 3 days (total of 4 possible messages if there are separate tokens expiring in 4 consecutive days).
Since this is schedule based I'd create multiple access tokens with different dates and a few with the same date. Preferably setting dates that are soon and then at noon verifying that the reminders were sent to the default channel (iirc is #implementation). So all tokens with expiration date X should be in a single reminder post on days X-3 to X except weekends. Ones with expiration date X+1 should be posted on days X-2 to X+1. (Reason for the 3 days ahead of time is to catch tokens expiring on a Monday before the weekend)

**Comment by texastoast** [comment]
creating a token that expires tomorrow, will see if I get a notification today at noon.

**Comment by texastoast** [comment]
created 2 tokens that expire tomorrow, got notification at noon that both tokens expire tomorrow with instructions to update. Moving to Ready to ship.
