### ISSUE TITLE
Bug - `/poker decide` command - removes existing labels

### ISSUE THREAD

**Issue by pjdiiori** [revelrylabs/slax#328]
**I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

**What is the current behavior?**
- when using the `/poker decide` command, the `points:x` label is added to the issue, but existing labels are removed

**What is the expected behavior?**
- existing labels should not be removed

https://github.com/revelrylabs/slax/assets/67023368/910209fc-2c3a-4828-8ce5-ae338c38d6a7

**Comment by grossvogel** [comment]
weird... I thought we already found and fixed this bug 🤔

**Comment by pjdiiori** [comment]
huh

**Comment by BunnyDunker** [comment]
Yeah I thought I had already handled this bug, but I'm not finding the fix I wrote anywhere and it's not a big change so I'll just put it in real quick

**Comment by pjdiiori** [comment]
looks like this is fixed!
