### ISSUE TITLE
Slax - Poker - Format Improvement

### ISSUE THREAD

**Issue by Dschechner** [revelrylabs/slax#359]
## Background
Currently, there is no sorting logic for the estimates. Improving this format will allow for the team to more easily decipher the results of the poker and eliminate unnecessary features. The purpose of this ticket is to add a format that will include spaces and commas between the estimators names, sort the estimates by ascending score, count the total number of people who estimated. It would also be beneficial to only repeat the name under the scores of the estimators if that person makes an additional comment.

Old PokerBot Example with Formatting, Sorting, and only showing Scores with Comments:
![Screenshot 2023-12-04 at 11 40 16 AM](https://github.com/revelrylabs/slax/assets/145717280/f12c5804-dfdf-4809-9499-a16738026345)

Current Slax Example:
<img width="1114" alt="Screenshot 2023-12-04 at 11 52 50 AM" src="https://github.com/revelrylabs/slax/assets/58119095/0753d710-e1a7-4758-acf7-8482e1884148">

### Scenario: Improve Estimate Formatting & Sort by Ascending Scores
Given I am a team member
- [ ] When the estimates for a round are revealed
- [ ] Then I will see each team members name with spaces and commas in between team members
- [ ] And the estimates will be sorted by ascending scores

### Scenario: Only Show Scores with Comments Below Estimates
Given I am a team member
And I make a comment on my estimated score
- [ ] When my team is finished estimating
- [ ] And the poker results are revealed
- [ ] Then I only see scores with comments below the estimates
   - i.e. name(score): comment
- [ ] And I do not see name(score): null

**Comment by amandaphu** [comment]
@Dschechner lets include a screenshot of a _good_ example aka the thread i linked you from platform in aug

**Comment by amandaphu** [comment]
@Dschechner 
<img width="1016" alt="Screenshot 2023-12-04 at 11 29 10 AM" src="https://github.com/revelrylabs/slax/assets/58119095/218647f9-2278-44f3-bbc1-49cb803a8cc4">

**Comment by amandaphu** [comment]
looks great closing
