### ISSUE TITLE
Reveler - Retro Bot - Reports timeline of repo's issue movement through waffle columns

### ISSUE THREAD

**Issue by EdwardReed** [revelrylabs/slax#36]
## Background
Similar to #91, but this will show an overview of ticket movement between columns for a particular repo and timeframe. 

**Implementation Resources:** 
https://github.com/revelrylabs/slax
https://developer.github.com/v3/issues/events/#list-events-for-a-repository
https://github.com/BlakeWilliams/Elixir-Slack
https://tutorials.botsfloor.com/building-a-slack-bot-in-elixir-372d7cc62091
https://docs.waffle.io/docs/columns-1

## Scenario:
Given I am a team member 
- [ ] When I run `/ticket retro [repo] [date range]` command in slack (ex: `/ticket retro tss 2019-01-12..2019-01-18`) 
- [ ] Then I see the following info: 
   - [ ] `#xxxx` moved from "in progress" to "in review" on `date`
   - [ ] `x` tickets moved from "in review" to "QA"
   - [ ] `x` tickets moved from "QA" to "UAT"
   - [ ] `x` tickets moved from "QA" to "up next" (indicates QA kickback) 
   - [ ] `x` tickets moved from "UAT" to "up next" (indicates UAT kickback) 
   - [ ] `x` tickets that were labeled `blocked` while having the label "in progress", "in review", "QA" and the column label (so I can see which column it got blocked in) 

_ac from @alinelea_  https://github.com/revelrylabs/devtools/issues/122#issue-401977311

**Poker Notes:** 
- reviewed https://developer.github.com/v3/issues/events and https://docs.waffle.io/docs/columns-1
- waffle may not necessarily have its own API 
- so using `moved_columns_in_project` may be in regards to Github projects and not waffle 
- we may want to go with `labeled` instead since the columns have their own labels 
- jonathan (13): I feel like most work will be invested in project setup, authentication, deployment? From there, I believe GitHub’s API is pretty powerful, though we will be querying against a lot of individual issues (not sure what happens in case of N + 1 queries).
- later let's add: 
   - [ ] `x` tickets moved from "up next" to "in progress"

**Comment by alinelea** [comment]
closing in favor of https://github.com/revelrylabs/devtools/issues/123
