### ISSUE TITLE
Slax - Issue Lookup - Disable channels

### ISSUE THREAD

**Issue by BunnyDunker** [revelrylabs/slax#363]
It was requested that Slax be disabled in the Frame channel [LINK](https://revelrylabs.slack.com/archives/C045BPFTQ/p1701815861075339)
From my initial look it is not possible on the Slack App side of things, so the easiest way to achieve this would be to add a filter to ignore messages from certain channels. This can quickly be setup as a one off or hard coded piece or could quickly be added as a modal for easier crud functionality. (there's an easy way to create a selector with all the channels listed)

**Comment by bford002** [comment]
Completed and [QA'd](https://revelrylabs.slack.com/archives/C045BPFTQ/p1702505544817159?thread_ts=1701815861.075339&cid=C045BPFTQ) on 12/13/23
