### ISSUE TITLE
Bug: Bad grammar in poker bot

### ISSUE THREAD

**Issue by texastoast** [revelrylabs/slax#380]
## Description
Minor nit: when 2 users have estimated, the notification says "X and X has estimated", but it should say "have".

## Screenshots/Gifs
![Screenshot on 2024-01-23 at 11-43-11](https://github.com/revelrylabs/slax/assets/3815148/d17a6747-4008-429d-a4a2-5fb5a3a8b194)

**Comment by fmugha2** [comment]
we did it

<img width="530" alt="Screenshot 2024-04-09 at 12 27 38 PM" src="https://github.com/revelrylabs/slax/assets/35368412/49168687-f6f9-47e7-a96d-2cef0e49ba3a">
