### ISSUE TITLE
User - Issue/PR Lookup - Channel Integration

### ISSUE THREAD

**Issue by amandaphu** [revelrylabs/slax#382]
## Background
In the old issue lookup, we were able to connect projects/repos to specified channels so that we could just reference an issue by its number (i.e. #issue_number). Having to include the repo or the org/repo makes the shortcut, not as short.

### Scenario: Associating a GitHub repo with a Slack channel during token setup
Given I am a user in a Slack workspace
And I have a valid GitHub Fine Grained Access token with read access to issues and pull requests
- [ ] When I invoke the `/token` command to set up or manage tokens
- [ ] And I select an existing repo by including org/repo
- [ ] Or I decide to create a new repo in the modal that appears
- [ ] And I enter the access token and expiration date
- [ ] Then the bot should associate the GitHub repo with the current Slack channel by default
- [ ] And allow users to reference issues or PRs with just the #issue_number or $pr_number within the linked channel

### Scenario: Referencing linked repo issues or PRs globally within all channels
Given I am a user in a Slack workspace
And a repo is already associated with a specific channel
- [ ] When I reference an issue or PR from the associated repo using repo#issue_number or org/repo#issue_number or repo$pr_number or org/repo$pr_number format
- [ ] Then Slax should reference the issue or PR in any channel, regardless of where the repo was initially connected 

 _created by amanda.phu+prodops@revelry.co using [Prodops](https://app.prodops.ai)_

**Comment by amandaphu** [comment]
From the description and the provided code snippets, it seems the Slax program is designed to work with both Slack and GitHub, allowing for various operations including creating issues, starting sprints, and handling issue references within messages. The goal is to enhance the referencing system by associating GitHub repositories with Slack channels to simplify referencing issues and pull requests.

To achieve this, we need the following capabilities:

1. Storing association of GitHub repositories with Slack channels.
2. Parsing messages to detect issue references (#issue_number or $pr_number) and intelligently linking them to the associated repository.
3. Handling global references by also understanding org/repo#issue_number or repo$pr_number formats.

Here's a code example to demonstrate how to create an association between a GitHub repository and a Slack channel:

```elixir
defmodule Slax.RepoChannelAssociation do
  use Slax.Context

  alias Slax.{Association, Github, Slack}

  def associate_repo_to_channel(repo, channel, token, expiration_date) do
    case get_association_by_channel(channel) do
      nil ->
        create_association(repo, channel, token, expiration_date)

      association ->
        update_association(association, repo, token, expiration_date)
    end
  end

  defp create_association(repo, channel, token, expiration_date) do
    %Association{}
    |> Association.changeset(%{
        repo_name: repo,
        channel_name: channel,
        access_token: token,
        token_expiration_date: expiration_date
      })
    |> Repo.insert()
  end

  defp update_association(association, repo, token, expiration_date) do
    association
    |> Association.changeset(%{
        repo_name: repo,
        access_token: token,
        token_expiration_date: expiration_date
      })
    |> Repo.update()
  end

  defp get_association_by_channel(channel) do
    Repo.get_by(Association, channel_name: channel)
  end
end
```

And to handle message events with issue or pull request references:

```elixir
defmodule SlaxWeb.Issue do
  # ... [rest of code] ...

  def handle_event(%{"channel" => channel, "text" => text, "type" => "message"}) do
    association = Slax.RepoChannelAssociation.get_association_by_channel(channel)
    
    if association do
      issues_scan = scan_text_for_issue(text, association.repo_name)
      prs_scan = scan_text_for_pr(text, association.repo_name)
    else
      issues_scan = scan_text_for_global_reference(text)
      prs_scan = scan_text_for_global_pr_reference(text)
    end

    # ... [rest of code already provided that sends the message] ...
  end

  defp scan_text_for_issue(text, repo_name) do
    Regex.scan(~r{(?<![\w-/])(#\d+)}, text)
    |> Enum.map(fn [match] -> "#{repo_name}#{match}" end)
  end

  defp scan_text_for_pr(text, repo_name) do
    Regex.scan(~r{(?<![\w-/])(\$\d+)}, text)
    |> Enum.map(fn [match] -> "#{repo_name}#{match}" end)
  end

  defp scan_text_for_global_reference(text) do
    Regex.scan(~r{([\w-]+/)?([\w-]+)(#\d+)}, text)
  end

  defp scan_text_for_global_pr_reference(text) do
    Regex.scan(~r{([\w-]+/)?([\w-]+)(\$\d+)}, text)
  end
end
```

The `scan_text_for_issue` and `scan_text_for_pr` functions were modified to prepend the repository name to the issue or PR number if an association exists. If no association exists for the channel, we fall back to a global reference scan.

This logic should be expanded upon to fully meet the requirements and integrate seamlessly with the rest of the system. This might involve enhancements to the way issues are stored or how the system reacts to commands in Slack. Database schemas, Ecto changesets, and other considerations also need to be fleshed out to make the solution fully operational.

Please note that additional logic not included in this snippet must be implemented to support the `/token` command and handle its interaction flow as per the acceptance criteria. 

 _created by amanda.phu+prodops@revelry.co using [Prodops](https://app.prodops.ai)_

**Comment by quinnmccourt** [comment]
Pr for the work dan has done is here: https://github.com/revelrylabs/slax/pull/404
